//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Account
    {
        public long Id { get; set; }
        public long UserId { get; set; }
        public string AccountName { get; set; }
        public string Username { get; set; }
        public string PasswordHint { get; set; }
        public string Password { get; set; }
        public Nullable<bool> ShowUsername { get; set; }
        public string PrivateKey { get; set; }
        public Nullable<bool> UsePrivateKey { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public System.DateTime CreationDate { get; set; }
        public System.DateTime ModifiedDate { get; set; }
    
        public virtual User User { get; set; }
    }
}
